### ISSUE TITLE
Game freezes while trying to load an object's material

### ISSUE THREAD

**Issue by pdr52** [THE-FYP/SAMP.Lua#6]
After joining a specific server, I noticed that the game would always freeze right before the login screen, after researching a bit more i found that SAMP.lua was trying to load an object's material indefinitely, thus causing the game to freeze infinitely.

Steps to reproduce:

1- Use [this script](https://gist.github.com/pdr52/5eb0761ac7f6246ce52192b6f18c9eb3)
2- Join this server: server.cod-rww.com:7777
3- Wait a bit and see your game freeze.

The problem seems to be in [this](https://github.com/THE-FYP/SAMP.Lua/blob/master/samp/events/handlers.lua#L529) line, [putting some prints in the code](https://gist.github.com/pdr52/09569a6d40a38ce5cb424f154d24042f) i get this:

<details>
test_1: while start<br/>
test_1: while iteration x1   6<br/>
test_1: while iteration x2   6<br/>
test_1: while iteration x3   6<br/>
..<br/>
test_1: while iteration x89   6<br/>
..<br/>
infinitely.
</details><br/>

I don't know if the solution would be to use raknetBitStreamIgnoreBits or something as i know nothing about the internals of SAMP, can you help me @THE-FYP? Thanks.

**Comment by THE-FYP** [comment]
Thanks for the report and sorry for no answer for long.
For some reason there was an excess bits in the packet, which is not enough to read a full 8-bit value, so reading and following conditions falls and loop goes infinite. This behavior is unusual for normal samp server, I suppose it was because of server's anticheat.
Should be fine now, reinstall from the source code.
